version: '2'
services:
  agarathi-app:
    image: agarathi
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://agarathi-postgresql:5432/agarathi
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://agarathi-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://agarathi-elasticsearch:9200
    ports:
      - 8080:8080
  agarathi-postgresql:
    extends:
      file: postgresql.yml
      service: agarathi-postgresql
  agarathi-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: agarathi-elasticsearch
